Algoritmo "Vetores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Emeldito Covane 
// Descrição   : Vectores
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/27/2022



Var
nomes: vetor[0..9] de caracter
posicao: inteiro


Inicio
para posicao de 0 ate 9 faca
	escreva("Nome do Vendedor: ")
	leia(nomes[posicao])
fimpara

para posicao de 0 ate 9 faca
	escreval("A posição", posicao, " do vetor, contém o nome: ", nomes[posicao])
fimpara


Fimalgoritmo